version: '3.1'
services:
  app-pm2: 
    image: node:12-alpine
    working_dir: /usr/src/app
    volumes:
      - ./static:/usr/src/app/static
      - ./backend:/usr/src/app
    ports:
      - 7000:7001
    env_file: .env # 环境变量env，我们写入到了配置文件里，避免密码泄漏
    command: sh -c "npm install && npm run dev"
    # networks:
    #   - nodeapp-network
  mysql:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mz_service
    ports:
      - 3306:3306
    # networks:
    #   - nodeapp-network

# networks:
#   nodeapp-network:
#     driver: bridge
      
  # nginx:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./static:/usr/src/app/static
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./frontend:/var/www/html/
  #   ports:
  #     - 8080:80